name: Build & Test

on:
  push:
    branches:
      - main
      - develop
      - "feature/**"
      - "release/**"
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        release: [Debug, Release]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v6

      - uses: actions/github-script@v8
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

      # Non-Windows

      - name: Configure CMake (non-Windows)
        if: matrix.os != 'windows-latest'
        run: >
          cmake -G Ninja -B build -DCMAKE_BUILD_TYPE=${{ matrix.release }} \
            -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DENABLE_TESTING=ON -DENABLE_EXAMPLES=ON

      - name: Build (non-Windows)
        if: matrix.os != 'windows-latest'
        run: cmake --build build

      - name: Install (non-Windows)
        if: matrix.os != 'windows-latest'
        run: sudo cmake --install build

      # Windows

      - name: Configure CMake (Windows)
        if: matrix.os == 'windows-latest'
        run: >
          cmake -B build -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake \
            -DENABLE_TESTING=ON -DENABLE_EXAMPLES=ON

      - name: Build (Windows)
        if: matrix.os == 'windows-latest'
        run: cmake --build build -j 8 --config ${{ matrix.release }}

      - name: Install (Windows)
        if: matrix.os == 'windows-latest'
        run: cmake --install build  --config ${{ matrix.release }}

      - name: Test
        if: matrix.os != 'windows-latest'
        run: ctest --test-dir build --output-on-failure

      - name: Examples
        if: matrix.os != 'windows-latest'
        run: ./build/examples/simple_mapper/simple_mapper

      - name: Archive example trace
        if: matrix.os != 'windows-latest'
        uses: actions/upload-artifact@v7
        with:
          name: example-trace-${{ matrix.os }}-${{ matrix.release }}
          path: trace.json
